### PR TITLE
Adds German language

### PR DESCRIPTION
**Pull request by kdomke**
Hi, as I need it myself, I created the translation to German. Maybe you want to include it.

Nice module :-)

---
* adds language file
* adds entry in module.json

### CODE REVIEW

**Comment by kdomke** [comment]
hm. This still does not add the small time setting to my scene configuration. Any Idea why it is missing there, if I am using German?

**Comment by unsoluble** [comment]
Ah! Good catch on the Scene Config localization requirement. I'll have to take a look at the API to see whether my (admittedly hacky) string matching there will be able to match against translated strings as well.

**Comment by unsoluble** [comment]
Hmm. Seems to work for me?

Screen Shot 2021-05-11 at 8 49 23 AM

**Comment by kdomke** [comment]
OK. I really had to restart the complete server. Restarting the world was not enought. 

Nevermind, Thanks :-) 

(btw: I hacked your string maching, but I had no idea how to do that in japanese....)

**Comment by unsoluble** [comment]
Note there are a bunch of new strings (lines 23-30 in en.json) that could use a translation if you're into that. :)

**Pull request merged**
